language: node_js
os:
  - osx
  - linux
node_js: 8

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn
  - cd server && yarn && cd ..
  - cd vti && yarn && cd ..

script:
  - yarn test

after_success:
  - cd server && yarn coverage && cd ..

cache: yarn
